//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeiWeiAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatBar
    {
        public int CId { get; set; }
        public Nullable<int> Cgroup { get; set; }
        public string Cchat { get; set; }
        public Nullable<int> CpostId { get; set; }
        public Nullable<System.DateTime> CpostTime { get; set; }
    
        public virtual ChatCreate ChatCreate { get; set; }
        public virtual Member Member { get; set; }
    }
}
