//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeiWeiAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberLife
    {
        public int MLid { get; set; }
        public Nullable<int> MLNumber { get; set; }
        public string MLName { get; set; }
        public string MLSex { get; set; }
        public string MLBirYear { get; set; }
        public string MLBirMonth { get; set; }
        public string MLBirDate { get; set; }
        public string MLBirTime { get; set; }
        public string MLLife { get; set; }
        public string MLMove { get; set; }
        public string MLMoney { get; set; }
        public string MLCompany { get; set; }
        public string MLCouple { get; set; }
        public string MLLucky { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
