//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeiWeiAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ZeiWeiEntities : DbContext
    {
        public ZeiWeiEntities()
            : base("name=ZeiWeiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChatBar> ChatBar { get; set; }
        public virtual DbSet<ChatCreate> ChatCreate { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<MemberLife> MemberLife { get; set; }
    
        [DbFunction("ZeiWeiEntities", "getMemberdata")]
        public virtual IQueryable<getMemberdata_Result> getMemberdata(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getMemberdata_Result>("[ZeiWeiEntities].[getMemberdata](@id)", idParameter);
        }
    
        public virtual int registerZeiWeiMember(string mAccount, string mPassword)
        {
            var mAccountParameter = mAccount != null ?
                new ObjectParameter("MAccount", mAccount) :
                new ObjectParameter("MAccount", typeof(string));
    
            var mPasswordParameter = mPassword != null ?
                new ObjectParameter("MPassword", mPassword) :
                new ObjectParameter("MPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("registerZeiWeiMember", mAccountParameter, mPasswordParameter);
        }
    
        public virtual int validationZeiWeiMember(string mAccount, string mPassword)
        {
            var mAccountParameter = mAccount != null ?
                new ObjectParameter("MAccount", mAccount) :
                new ObjectParameter("MAccount", typeof(string));
    
            var mPasswordParameter = mPassword != null ?
                new ObjectParameter("MPassword", mPassword) :
                new ObjectParameter("MPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("validationZeiWeiMember", mAccountParameter, mPasswordParameter);
        }
    }
}
